site_name: Hierarchical Event Descriptors (HED v8.0.0)
site_url: https://hed-specification.readthedocs.io/en/stable/
theme:
    name: material
    custom_dir: theme_customizations/
    favicon: images/favicon.png
    logo: images/logo.png
extra_javascript:
    - js/jquery-3.4.1.min.js
markdown_extensions:
    - toc:
        anchorlink: true
    - pymdownx.superfences
plugins:
    - search
    - branchcustomization:
        update_config:
         - branch: /(?!^master$)/
           +extra_css:
             - css/watermark.css

docs_dir: 'hedspec'
use_directory_urls: false
nav:
    - The HED Specification:
      - All: HEDspecification.md
    - The HED ecosystem:
      - GitHub specification repository: https://github.com/hed-standard/bids-starter-kit
      - HED home: https://www.hedtags.org
      - HED online tools: https://hedtools.ucsd.edu/hed